# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: CI

on:
  push:
    branches: main
    paths-ignore:
    - 'README.md'
  pull_request:
    branches: main
    paths-ignore:
    - 'README.md'

jobs:
  build:
    # https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#jobsjob_idif
    if: github.repository == 'release-engineering/opentelemetry-ext-cli-java' && github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - name: Cache local Maven repository
      uses: actions/cache@v4
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Set up JDK 17
      uses: actions/setup-java@v5
      with:
        distribution: 'temurin'
        java-version: 17
    - name: Build with Maven
      run: mvn -B -V install
    # - name: Setup tmate session
    #   uses: mxschmitt/action-tmate@v3
    - name: Codecov
      uses: codecov/codecov-action@v5

  snapshot:
    if: github.repository == 'release-engineering/opentelemetry-ext-cli-java' && github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - name: Cache local Maven repository
      uses: actions/cache@v4
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Set up JDK 17
      uses: actions/setup-java@v5
      with:
        distribution: 'temurin'
        java-version: 17
    # https://github.com/marketplace/actions/maven-setings-action
    - name: Maven Settings
      uses: s4u/maven-settings-action@v4.0.0
      with:
        sonatypeSnapshots: true
        githubServer: false
        servers: |
            [{
                "id": "central",
                "username": "${{ secrets.SONATYPE_USERNAME }}",
                "password": "${{ secrets.SONATYPE_PASSWORD }}"
            }]
    - name: Deploy Snapshot
      run: mvn -B -V org.apache.maven.plugins:maven-source-plugin:jar-no-fork deploy
